[meta]
version = 2026.6
description = "An open-source IRC client for Mac, Windows, and Linux, focused on being simple and fast."
name = "halloy"
pkgt= 0
[package]
source = "https://github.com/squidowl/halloy"
command = "cargo build --release"
finbin = "target/release/halloy"
